apiVersion: v2
appVersion: v0.3.1
description: |
    Hajimari is a beautiful & customizable browser startpage/dashboard with 
    Kubernetes application discovery
name: hajimari
version: 2.0.2
kubeVersion: ">=1.16.0-0"
keywords:
- hajimari
- startpage
- dashboard
icon: https://raw.githubusercontent.com/toboshii/hajimari/main/assets/logo.png

maintainers:
- name: toboshii
  email: toboshii@users.noreply.github.com
dependencies:
- name: common
  # version: 0.2.2
  version: 2.3.0
  repository: https://bjw-s.github.io/helm-charts/