apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  ignoreDifferences:
  - group: "apiextensions.k8s.io"
    kind: "CustomResourceDefinition"
    jsonPointers:
    - /spec/conversion/webhook/clientConfig

  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true

  source:
    path: localApps/kusto-argo
    repoURL: https://github.com/rdartus/k3s-argo2.git
    targetRevision: main
  destination:
    server: {{ .Values.dest_server }}
    namespace: argocd