{{- include "bjw-s.common.loader.init" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" .  }}-settings
  labels: 
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}

data:
  config.yaml: |-
{{ toYaml .Values.hajimari | indent 4 }}